In [1]:
import numpy as np

In [2]:
x = np.array([[0, 0, 1, 1],
            [1, 0, 0, 0],
            [0, 1, 1, 0],
            [0, 0, 0, 1]])

w = np.array([
    [0.2, 0.4, 0.6, 0.8],
    [0.9, 0.7, 0.5, 0.3]
])

lr = 0.5

In [3]:
epochs = 1
for e in range(epochs):
    print(f"\nEpoch {e+1}")
    print(f"Learning Rate: ",lr)
    for i in range(len(x)):
        print(f"\nInput {i+1}: {x[i]}")

        distances = ((w - x[i])**2).sum(axis=1)

        bmu = np.argmin(distances)

        print("Distances:",distances)
        print("BMU:",bmu+1)

        w[bmu] = w[bmu] + lr*(x[i] - w[bmu])

        print("Updated Weights:\n",w)

    lr *= 0.5


Epoch 1
Learning Rate:  0.5

Input 1: [0 0 1 1]
Distances: [0.4  2.04]
BMU: 1
Updated Weights:
 [[0.1 0.2 0.8 0.9]
 [0.9 0.7 0.5 0.3]]

Input 2: [1 0 0 0]
Distances: [2.3  0.84]
BMU: 2
Updated Weights:
 [[0.1  0.2  0.8  0.9 ]
 [0.95 0.35 0.25 0.15]]

Input 3: [0 1 1 0]
Distances: [1.5  1.91]
BMU: 1
Updated Weights:
 [[0.05 0.6  0.9  0.45]
 [0.95 0.35 0.25 0.15]]

Input 4: [0 0 0 1]
Distances: [1.475 1.81 ]
BMU: 1
Updated Weights:
 [[0.025 0.3   0.45  0.725]
 [0.95  0.35  0.25  0.15 ]]
